[server]
# 设置服务器地址为0.0.0.0，允许通过内网IP访问
address = "0.0.0.0"
port = 8501

# 禁用浏览器自动打开
headless = true

# 禁用使用统计收集
gatherUsageStats = false

# 设置文件监视器类型（减少资源占用）
fileWatcherType = "none"

# 禁用自动重新运行
runOnSave = false

[browser]
# 禁用使用统计收集
gatherUsageStats = false

# 设置服务器地址显示
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# 可选：设置主题颜色
# primaryColor = "#FF6B6B"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730"

[logger]
# 设置日志级别
level = "info"